# Eyetor Windows Service installer
# Installs Eyetor as a Windows service using NSSM (Non-Sucking Service Manager)
# or as a scheduled task if NSSM is not available.
#
# Run as Administrator:
#   powershell -ExecutionPolicy Bypass -File windows\install-service.ps1
#
# For the Telegram bot (recommended for 24/7):
#   powershell -ExecutionPolicy Bypass -File windows\install-service.ps1 -Mode telegram
#
# To uninstall:
#   powershell -ExecutionPolicy Bypass -File windows\install-service.ps1 -Action uninstall

param(
    [string]$Mode   = "telegram",   # "telegram" | "chat"
    [string]$Action = "install"     # "install" | "uninstall" | "status"
)

$ServiceName = "EyetorAgent-$Mode"
$ProjectDir  = Split-Path -Parent $PSScriptRoot
$PythonExe   = (Get-Command python -ErrorAction SilentlyContinue).Source
$EyetorExe   = (Get-Command eyetor  -ErrorAction SilentlyContinue).Source
$EnvFile     = Join-Path $ProjectDir ".env"
$LogDir      = Join-Path $env:LOCALAPPDATA "Eyetor\logs"

# ---- Validation ----
if (-not $PythonExe) {
    Write-Error "Python not found. Install Python 3.11+ and add it to PATH."
    exit 1
}
if (-not $EyetorExe) {
    Write-Warning "eyetor command not found in PATH. Trying to install..."
    & pip install -e "$ProjectDir" --quiet
    $EyetorExe = (Get-Command eyetor -ErrorAction SilentlyContinue).Source
    if (-not $EyetorExe) {
        Write-Error "Could not find 'eyetor' after install. Run: pip install -e $ProjectDir"
        exit 1
    }
}

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# ---- Status ----
if ($Action -eq "status") {
    $nssm = Get-Command nssm -ErrorAction SilentlyContinue
    if ($nssm) {
        & nssm status $ServiceName
    } else {
        $task = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
        if ($task) {
            Write-Host "Task Scheduler task '$ServiceName': $($task.State)"
        } else {
            Write-Host "Service '$ServiceName' not found."
        }
    }
    exit 0
}

# ---- Uninstall ----
if ($Action -eq "uninstall") {
    $nssm = Get-Command nssm -ErrorAction SilentlyContinue
    if ($nssm) {
        Write-Host "Stopping and removing NSSM service: $ServiceName"
        & nssm stop $ServiceName 2>$null
        & nssm remove $ServiceName confirm
    } else {
        Write-Host "Removing scheduled task: $ServiceName"
        Unregister-ScheduledTask -TaskName $ServiceName -Confirm:$false -ErrorAction SilentlyContinue
    }
    Write-Host "Uninstalled."
    exit 0
}

# ---- Install ----

# Load .env file variables into current session (for the service environment)
$EnvVars = @{}
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | Where-Object { $_ -match '^\s*([^#][^=]+)=(.*)$' } | ForEach-Object {
        $parts = $_ -split '=', 2
        $EnvVars[$parts[0].Trim()] = $parts[1].Trim()
    }
} else {
    Write-Warning ".env not found at $EnvFile. Service will use system environment variables."
}

$CmdArgs = $Mode  # "telegram" or "chat"

# Try NSSM first (best option)
$nssm = Get-Command nssm -ErrorAction SilentlyContinue
if ($nssm) {
    Write-Host "Installing with NSSM: $ServiceName"

    & nssm install $ServiceName $EyetorExe $CmdArgs
    & nssm set $ServiceName AppDirectory $ProjectDir
    & nssm set $ServiceName DisplayName "Eyetor Agent ($Mode)"
    & nssm set $ServiceName Description "Eyetor multi-agent AI system — $Mode mode"
    & nssm set $ServiceName Start SERVICE_AUTO_START
    & nssm set $ServiceName AppStdout (Join-Path $LogDir "$ServiceName-stdout.log")
    & nssm set $ServiceName AppStderr (Join-Path $LogDir "$ServiceName-stderr.log")
    & nssm set $ServiceName AppRotateFiles 1
    & nssm set $ServiceName AppRotateBytes 10485760  # 10MB

    # Set environment variables from .env
    foreach ($key in $EnvVars.Keys) {
        & nssm set $ServiceName AppEnvironmentExtra "$key=$($EnvVars[$key])"
    }

    & nssm start $ServiceName
    Write-Host "Service '$ServiceName' installed and started."
    Write-Host "Logs: $LogDir"
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  nssm status $ServiceName"
    Write-Host "  nssm stop   $ServiceName"
    Write-Host "  nssm start  $ServiceName"
    Write-Host "  nssm restart $ServiceName"

} else {
    # Fallback: Task Scheduler (runs at system startup, as current user)
    Write-Host "NSSM not found. Installing with Task Scheduler: $ServiceName"
    Write-Host "(Install NSSM from https://nssm.cc for better service management)"

    # Build environment block for the task
    $EnvString = ($EnvVars.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "`n"

    # Wrapper script that sets env vars and runs eyetor
    $WrapperScript = Join-Path $LogDir "run-$ServiceName.ps1"
    $WrapperContent = @"
# Auto-generated by Eyetor installer
Set-Location '$ProjectDir'
$(($EnvVars.GetEnumerator() | ForEach-Object { "`$env:$($_.Key) = '$($_.Value)'" }) -join "`n")
& '$EyetorExe' $CmdArgs *>> '$LogDir\$ServiceName.log'
"@
    Set-Content -Path $WrapperScript -Value $WrapperContent -Encoding UTF8

    $action  = New-ScheduledTaskAction -Execute "powershell.exe" `
                 -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$WrapperScript`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet `
        -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -StartWhenAvailable

    Register-ScheduledTask -TaskName $ServiceName `
        -Action $action -Trigger $trigger -Settings $settings `
        -Description "Eyetor AI Agent — $Mode mode" `
        -RunLevel Highest -Force | Out-Null

    Start-ScheduledTask -TaskName $ServiceName
    Write-Host "Task '$ServiceName' registered and started."
    Write-Host "Logs: $LogDir\$ServiceName.log"
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  Get-ScheduledTask -TaskName '$ServiceName' | Select State"
    Write-Host "  Start-ScheduledTask  '$ServiceName'"
    Write-Host "  Stop-ScheduledTask   '$ServiceName'"
}

Write-Host ""
Write-Host "Download NSSM (recommended): https://nssm.cc/download"
